name: docker
run-name: auto build image

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 1 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      TAG: 2001-01-01
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        ref: 'main'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get Date
      run: echo "TAG=$(date +%Y-%m-%d)" >> "$GITHUB_ENV"
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          leenhawk/cloudflare_warp:latest
          leenhawk/cloudflare_warp:${{env.TAG}}